HomePets.WebApp/HomePets.WebApp/Controllers/DonoController.cs
using HomePets.WebApp.Domain.Models;
using HomePets.WebApp.Infra.Interfaces;
using HomePets.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomePets.WebApp.Controllers
{
    public class DonoController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;

        public DonoController(IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }

        public async Task<IActionResult> Index()
        {
            var model = new List<UsuarioModel>();
            var lista_donos = await _usuarioRepository.ListarDonos();

            if (lista_donos.Any())
            {
                foreach(var item in lista_donos)
                {
                    model.Add(new UsuarioModel(item));
                }
            }

            return View(model);
        }

        public IActionResult Create()
        {
            var model = new UsuarioModel();
            model.TipoUsuario = Domain.Models.TipoUsuario.DonoPet;
            return View(model);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var dono = await _usuarioRepository.ObterUsuarioPorId(id);
            var model = new UsuarioModel(dono);
            return View("Create", model);
        }

        public async Task<IActionResult> Insert(UsuarioModel model)
        {
            var sucesso = false;
            var usuario = MontarEntidade(model);

            if (model.Id != null)
                sucesso = await _usuarioRepository.AtualizarUsuario(usuario);
            else
                sucesso = await _usuarioRepository.CadastrarUsuario(usuario);

            if (sucesso)
                return RedirectToAction("Index", "DonoPet");
            else
                return View("Create", model);
        }

        private Usuario MontarEntidade(UsuarioModel model)
        {
            return new Usuario
            {
                Id = model.Id.HasValue ? model.Id.Value : Guid.NewGuid(),
                TipoUsuario = model.TipoUsuario,
                Bairro = model.Bairro,
                Cidade = model.Cidade,
                Cpf = model.Cpf,
                Email = model.Email,
                Nome = model.Nome,
                Telefone = model.Telefone
            };
        }
    }
}

HomePets.WebApp/HomePets.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomePets.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HomePets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Passeador" asp-action="Index">Área de Passeadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AgendaPasseio" asp-action="Index">Solicitações de Passeios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dono" asp-action="Index">Área de Donos de Pets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Passeio" asp-action="Index">Passeios Ativos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HomePets.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>